<a href="https://colab.research.google.com/github/phuongnt3391/ArtificialNeuralNetwork/blob/main/ArtificialNeuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
tf.__version__

'2.5.0'

Data Preprocessing

In [3]:
df = pd.read_csv('Churn_Modelling.csv')

Encoding the categorical data

In [4]:
df.columns

Index(['CustomerId', 'Surname', 'CreditScore', 'Geography', 'Gender', 'Age',
       'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard', 'IsActiveMember',
       'EstimatedSalary', 'Exited'],
      dtype='object')

In [5]:
df.head()

CustomerId   Surname  CreditScore  ... IsActiveMember EstimatedSalary  Exited
0    15634602  Hargrave          619  ...              1       101348.88       1
1    15647311      Hill          608  ...              1       112542.58       0
2    15619304      Onio          502  ...              0       113931.57       1
3    15701354      Boni          699  ...              0        93826.63       0
4    15737888  Mitchell          850  ...              1        79084.10       0

[5 rows x 13 columns]

In [31]:
df.isnull().sum()

CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [55]:
X = df.iloc[:,2:-1].values
y = df.iloc[:,-1].values

In [56]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [57]:
print(y)

[1 0 1 ... 1 1 0]


Encode 'Gender' variable

In [58]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2]) 

In [59]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Encode 'Geography' variable


In [88]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [89]:
print(X)

[[1.0 0.0 1.0 ... 1 1 101348.88]
 [1.0 0.0 0.0 ... 0 1 112542.58]
 [1.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 1.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 1.0 ... 1 0 38190.78]]


Split the dataset

In [68]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [69]:
print(X_train)

[[0.0 0 1.0 ... 1 0 163830.64]
 [0.0 1 0.0 ... 1 1 57098.0]
 [1.0 0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0 0.0 ... 1 0 181429.87]
 [0.0 0 1.0 ... 1 1 148750.16]
 [0.0 1 0.0 ... 1 0 118855.26]]


In [70]:
print(X_test)

[[0.0 1 0.0 ... 1 1 192852.67]
 [1.0 0 0.0 ... 1 0 128702.1]
 [0.0 0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0 1.0 ... 1 0 141533.19]
 [0.0 1 0.0 ... 1 1 11276.48]
 [0.0 1 0.0 ... 1 0 192950.6]]


Feature Scaling

In [71]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()


In [72]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [73]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [74]:
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


Building the ANN

In [75]:
ann = tf.keras.models.Sequential()

Adding the input layer and the 1st hidden *layer* 

In [76]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the 2nd hidden layer 

In [77]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

Adding the output layer

In [78]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

Training the ANN

Compiling the ANN

In [79]:
ann.compile(optimizer='adam',loss = 'binary_crossentropy', metrics=['accuracy'])

Training the ANN on the training set

In [80]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5444 - accuracy: 0.7870
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4685 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4437 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4252 - accuracy: 0.7965
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4094 - accuracy: 0.8027
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3970 - accuracy: 0.8075
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3872 - accuracy: 0.8106
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3776 - accuracy: 0.8375
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3699 - accuracy: 0.8439
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3647 - accura

Making the predictions and evaluate the model

Predicting the result of a single observation

In [82]:
print(ann.predict(sc.transform([[600, 1.0, 0.0, 0.0,1,40,3,60000,2,1,1,50000]])) >0.5)

[[False]]


Predicting the Test set result

In [83]:
y_pred = ann.predict(X_test)
y_pred = (y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


Making the Confusion matrix

In [84]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.89      0.95      0.92      1595
           1       0.72      0.52      0.60       405

    accuracy                           0.86      2000
   macro avg       0.80      0.73      0.76      2000
weighted avg       0.85      0.86      0.85      2000



In [85]:
print(confusion_matrix(y_test,y_pred))

[[1513   82]
 [ 195  210]]
